# Generated by Django 3.2.7 on 2021-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('shareMessage', models.TextField(blank=True, null=True)),
                ('idGSheet', models.CharField(blank=True, max_length=270, null=True)),
                ('shared', models.BooleanField(default=True)),
            ],
        ),
    ]
