# Generated by Django 3.2.7 on 2021-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parte',
            name='title',
            field=models.CharField(default='Semana 20 de octubre', max_length=70),
        ),
    ]
